# Generated by Django 6.0.3 on 2026-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_property_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingproperty',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_rules',
            field=models.CharField(choices=[('No smoking', 'No smoking'), ('Pets allowed', 'Pets allowed'), ('There is a safe', 'There is a safe'), ('Cleanliness and order', 'Cleanliness and order'), ('Careful attitude to property', 'Careful attitude to property'), ('Observance of silence', 'Observance of silence')], max_length=32),
        ),
    ]
