# Generated by Django 6.0.3 on 2026-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0003_alter_bookingproperty_guest_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_rules',
            field=models.CharField(blank=True, choices=[('No smoking', 'No smoking'), ('Pets allowed', 'Pets allowed'), ('There is a safe', 'There is a safe'), ('Cleanliness and order', 'Cleanliness and order'), ('Careful attitude to property', 'Careful attitude to property'), ('Observance of silence', 'Observance of silence')], max_length=32, null=True),
        ),
    ]
